solr_url:     http://apache-mirror.rbc.ru/pub/apache/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
solr_root:    /opt/solr-{{ solr_version }}
solr_tar:     /tmp/solr-{{ solr_version }}.tgz
