phantomjs_root: /opt/phantomjs-{{phantomjs_version}}-linux-x86_64
phantomjs_filename: phantomjs-{{phantomjs_version}}-linux-x86_64.tar.bz2
phantomjs_url: https://bitbucket.org/ariya/phantomjs/downloads/{{phantomjs_filename}}
phantomjs_archive: /tmp/phantomjs-{{phantomjs_version}}.tar.bz2
